# Generated by Django 5.0.6 on 2024-05-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
